services:
  db:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: gunaso
      MYSQL_USER: gunasouser
      MYSQL_PASSWORD: Gun@so@123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    restart: always
    volumes:
      - C:\backup\gunaso_backup:/var/lib/mysql
    networks:
      - gunaso_network

  migration:
    image: gunaso_app:latest
    profiles: [initialize]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    networks:
      - gunaso_network

  app:
    image: gunaso_app:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    networks:
      - gunaso_network

networks:
  gunaso_network: